"""Initial migration

Revision ID: c76d8be63fed
Revises: 
Create Date: 2025-09-10 16:59:30.251218

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76d8be63fed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('templates', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.add_column('templates', sa.Column('is_public', sa.Integer(), nullable=True))
    op.add_column('templates', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('templates', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('templates', sa.Column('business_size', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'business_size')
    op.drop_column('templates', 'industry')
    op.drop_column('templates', 'created_by')
    op.drop_column('templates', 'is_public')
    op.drop_column('templates', 'meta_data')
    op.drop_column('templates', 'tags')
    # ### end Alembic commands ###